export { default as AbstractMartix } from "./AbstractMartix"
export { default as Martix } from "./Martix"
export { default as Vector2 } from "./Vector2"
export { default as Vector3 } from "./Vector3"
export * as easy from "./Easy"